apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args:
        - "--cpu"
        - "4"
        - "--timeout"
        - "600"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
