apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: memory-stress-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: memory-stress # Match your deployment
  updatePolicy:
    updateMode: "Auto" # Options: Off | Initial | Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*" # Apply to all containers
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2
        memory: 2Gi
