apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8
  labels:
    app: yolov8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolov8
  template:
    metadata:
      labels:
        app: yolov8
    spec:
      containers:
        - name: yolov8
          image: atanda/yolov8-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"