apiVersion: v1
kind: Service
metadata:
  name: yolov8-service
spec:
  type: NodePort
  selector:
    app: yolov8
  ports:
    - port: 80           # external port (optional for health check)
      targetPort: 8000   # container port
      nodePort: 30080    # NodePort (must match ALB target group)