apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:obalola14/EKS-CICD.git'
    path: Custom-App # or 'charts/' if using Helm
    targetRevision: master #Branch it targets
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
