name: Build Docker Image and Deploy to EKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/yolov8-app.yml'
  workflow_dispatch:   # <<<<<< Manual trigger via GitHub UI

jobs:

  build-and-deploy-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: atanda/yolov8
      REGION: us-east-2
      CLUSTER_NAME: yolov8-cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ env.REGION }}

    # - name: Update kubeconfig for EKS
    #   run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION

    # - name: Apply Kubernetes Manifests
    #   run: |
    #     kubectl apply -f infra/config/yolov8.yaml
    #     kubectl apply -f infra/config/yolov8-service.yaml
    #     kubectl rollout status deployment/yolov8
    #     kubectl wait --for=condition=available --timeout=60s deployment/yolov8
        
    # - name: Update EKS Deployment with Latest Image
      run: |
        kubectl set image deployment/yolov8 yolov8=$IMAGE_NAME:latest
        kubectl rollout status deployment/yolov8